APMN = """
amiral	amiraux
animal	animaux
annal	annaux
anormal	anormaux
anticlérical	anticléricaux
arsenal	arsenaux
bocal	bocaux
canal	canaux
cantal	cantaux
capital	capitaux
caporal	caporaux
cardinal	cardinaux
central	centraux
chenal	chenaux
cheval	chevaux
clérical	cléricaux
collatéral	collatéraux
colonial	coloniaux
commensal	commensaux
communal	communaux
confessionnal	confessionnaux
cordial	cordiaux
corporal	corporaux
cristal	cristaux
cérébral	cérébraux
fanal	fanaux
frontal	frontaux
fédéral	fédéraux
féodal	féodaux
gardénal	gardénaux
général	généraux
hôpital	hôpitaux
idéal	idéaux
international	internationaux
journal	journaux
libéral	libéraux
local	locaux
madrigal	madrigaux
marsupial	marsupiaux
maréchal	maréchaux
mal	maux
minéral	minéraux
moral	moraux
méridional	méridionaux
métal	métaux
nasal	nasaux
national	nationaux
normal	normaux
numéral	numéraux
occidental	occidentaux
occipital	occipitaux
oral	oraux
ordinal	ordinaux
oriental	orientaux
original	originaux
piédestal	piédestaux
principal	principaux
provincial	provinciaux
quintal	quintaux
radical	radicaux
rival	rivaux
rural	ruraux
régional	régionaux
sentimental	sentimentaux
signal	signaux
social	sociaux
sénéchal	sénéchaux
temporal	temporaux
tergal	tergaux
total	totaux
tribunal	tribunaux
urinal	urinaux
vassal	vassaux
val	vaux
végétal	végétaux
véronal	véronals
éditorial	éditoriaux
égal	égaux
étal	étau
"""
