site_name: batchalign
theme:
  features:
    - navigation.expand
  name: material
  icon:
    logo: material/bank
  palette:
    primary: black

markdown_extensions:
    - mkdocs-click
extra:
  generator: false

copyright: Copyright &copy 2025, Brian MacWhinney and Houjun Liu; The TalkBank Project (NIH grant HD082736).
